name: Linuscys' Blog
description: Linuscys' Blog
meta_description: "Linuscys' Blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
